### ISSUE TITLE
HTTP and OS Error

### ISSUE THREAD

**Issue by salmaShahid** [MuhammadMoinFaisal/LargeLanguageModelsProjects#1]
While running the notebook.login() or huggingfacecli --login command, before initializing tokenizer; it will generate this error. tell me how can i solved it?

`HTTPError                                 Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_errors.py](https://localhost:8080/#) in hf_raise_for_status(response, endpoint_name)
    260     try:
--> 261         response.raise_for_status()
    262     except HTTPError as e:

10 frames
HTTPError: 403 Client Error: Forbidden for url: https://huggingface.co/meta-llama/Llama-2-7b-chat-hf/resolve/main/tokenizer_config.json

The above exception was the direct cause of the following exception:

GatedRepoError                            Traceback (most recent call last)
GatedRepoError: 403 Client Error. (Request ID: Root=1-64c511c2-242fa8811f9d12ed68e0914a;bb0a7569-d355-4f16-87b5-772d92fd3c30)

Cannot access gated repo for url https://huggingface.co/meta-llama/Llama-2-7b-chat-hf/resolve/main/tokenizer_config.json.
Access to model meta-llama/Llama-2-7b-chat-hf is restricted and you are not in the authorized list. Visit https://huggingface.co/meta-llama/Llama-2-7b-chat-hf to ask for access.

During handling of the above exception, another exception occurred:

OSError                                   Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/transformers/utils/hub.py](https://localhost:8080/#) in cached_file(path_or_repo_id, filename, cache_dir, force_download, resume_download, proxies, use_auth_token, revision, local_files_only, subfolder, repo_type, user_agent, _raise_exceptions_for_missing_entries, _raise_exceptions_for_connection_errors, _commit_hash)
    431 
    432     except RepositoryNotFoundError:
--> 433         raise EnvironmentError(
    434             f"{path_or_repo_id} is not a local folder and is not a valid model identifier "
    435             "listed on '[https://huggingface.co/models'\nIf](https://huggingface.co/models'/nIf) this is a private repository, make sure to "

OSError: meta-llama/Llama-2-7b-chat-hf is not a local folder and is not a valid model identifier listed on https://huggingface.co/models if this is a private repository, make sure to pass a token having permission to this repo with use_auth_token or log in with huggingface-cli login and pass use_auth_token=True . `

**Comment by MuhammadMoinFaisal** [comment]
I have already explained this point in video you can watch it 
Thanks
